version: "3.8"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend-api:
    build: ./backend-api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend-api:/backend-api
    ports:
      - "8000:8000"
    depends_on:
      - db
  app:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"