# Generated by Django 3.1.3 on 2020-11-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottlecaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
