# Generated by Django 3.1.3 on 2020-11-25 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bottlecaps', '0002_title_featured'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'title')},
        ),
    ]
