# Generated by Django 3.1.2 on 2020-11-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottlecaps', '0003_category_review_titles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('synopsis', models.TextField()),
                ('cover_image_path', models.URLField(blank=True, max_length=255, null=True)),
                ('user_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('user_review_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(related_name='titles', to='bottlecaps.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='Titles',
        ),
    ]
